### ISSUE TITLE
Exes

### ISSUE THREAD

**Issue by SzotsGabor** [adajed/chessplusplus#115]
Hi Adam,

I am unable to compile your engine. I am a complete stranger to CMake and trying

_g++ *.cpp -flto -O3 -march=native -oChessPlusPlus_1.2.0-x64-SzG.exe_

also failed because I got this type of error: 

_**In file included from endgame.h:4,
                 from bitbase.cpp:3:
position.h:9:10: fatal error: bits/stdint-uintn.h: No such file or directory
    9 | #include <bits/stdint-uintn.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from endgame.h:4,
                 from endgame.cpp:1:
position.h:9:10: fatal error: bits/stdint-uintn.h: No such file or directory
    9 | #include <bits/stdint-uintn.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.**_

Could you not provide exes for a couple of platforms?

Gabor

**Comment by adajed** [comment]
Have you tried `mkdir build && cd build && cmake .. && make -j8` ?
In what platforms are you interested in?

**Comment by SzotsGabor** [comment]
> Have you tried `mkdir build && cd build && cmake .. && make -j8` ? In what platforms are you interested in?

Yes. cmake .. produces this output:

_CMake Deprecation Warning at _deps/googletest-src/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at _deps/googletest-src/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions._

Then the "make... etc" command produces this:

_make: *** No rule to make target 'chessplusplus'.  Stop._


I am on 64-bit Windows 11.

**Comment by adajed** [comment]
Okey, I'll add binaries :)

**Comment by rwbc** [comment]
Hi Adam (and Gabor),

It's long time since my first issue ;)
Gabors problem is a bit related to something I mentioned in my first issue here.

I had to replace the two instances of includes (in the engine folder) with "bits/stdint-uintn.h" by "stdint.h" for WIN compilation.
And then I had to find/move the chessplusplusConfig.h file (renamed) from roots folder (demanded by "uci.cpp"), while I also
filled in appropriate values/names for the variables of course.

After this it compiled smoothly w/o any problems using
`g++ -O3 -Wall -std=c++17 -flto -march=native -static *.cpp -o chessplusplus_120GS.exe` in msys2.

Then I did a few tests from cmd with 'go depth' and 'go infinite' and it always crashed around depth 9-13,
giving some assert failure from an assert line in "position.cpp"

After compiling with an additional -DNDEBUG flag those crashes disappeared as I had hoped.


```
Chess engine by Adam Jedrych (build Nov  3 2023 13:43:00)
uci
id name chessplusplus 1.2.0 GS
id author Adam Jedrych

option name Logfile type string default
option name Polyglot Book type string default
option name Polyglot Sample type combo default random var random var best
uciok
isready
readyok
position startpos
go infinite
info depth 1 score cp 67 nodes 27 nps 27000 tbhits 0 hashfull 0 time 0 pv e2e4
info depth 2 score cp 0 nodes 115 nps 19166 tbhits 0 hashfull 0 time 5 pv e2e4 e7e5
info depth 3 score cp 34 nodes 871 nps 62214 tbhits 65 hashfull 0 time 13 pv d2d4 d7d5 g1f3
info depth 4 score cp 6 nodes 3506 nps 120896 tbhits 263 hashfull 1 time 28 pv e2e4 d7d5 b1c3 g8f6
info depth 5 score cp 31 nodes 8985 nps 154913 tbhits 351 hashfull 1 time 57 pv d2d4 d7d5 g1f3
info depth 6 score cp 0 nodes 33443 nps 207720 tbhits 1852 hashfull 2 time 160 pv d2d4 d7d5 g1f3 g8f6
info depth 7 score cp 28 nodes 56271 nps 176952 tbhits 2037 hashfull 2 time 317 pv g1f3 d7d5 d2d4 g8f6 b1c3 b8c6 c1f4
info depth 8 score cp 7 nodes 147880 nps 199568 tbhits 5207 hashfull 5 time 740 pv e2e4 d7d5 e4e5 b8c6 d2d4 a7a6 b1c3 c8f5
info depth 9 score cp 8 nodes 200157 nps 154800 tbhits 6667 hashfull 8 time 1292 pv g1f3 d7d5 d2d4
info depth 10 score cp 10 nodes 826296 nps 232693 tbhits 29493 hashfull 31 time 3550 pv e2e4 d7d5 e4d5 d8d5 b1c3 d5e6 d1e2 e6e2 f1e2
info depth 11 score cp 10 nodes 436914 nps 93118 tbhits 15797 hashfull 39 time 4691 pv e2e4 d7d5 e4d5
info depth 12 score cp 17 nodes 1113860 nps 144525 tbhits 37141 hashfull 67 time 7706 pv e2e4 d7d5 e4d5 d8d5 b1c3 d5e6 f1e2 e6g6 g1f3 b8c6 c3b5 g6g2
info depth 13 score cp 19 nodes 1577673 nps 132455 tbhits 63124 hashfull 104 time 11910 pv e2e4 d7d5 e4d5 d8d5 b1c3 d5e6 d1e2 b8c6 g1f3 g8f6 d2d4 h7h6 c1f4 c6b4
info depth 14 score cp 27 nodes 5956861 nps 212063 tbhits 171697 hashfull 221 time 28089 pv e2e4 c7c5 b1c3 b8c6
info depth 15 score cp 20 nodes 7343543 nps 152713 tbhits 239644 hashfull 328 time 48086 pv e2e4 c7c5 b1c3 b8c6 g1f3 g8f6 d2d4 c5d4 f3d4 e7e5 d4c6 d7c6 d1d8 e8d8

```
(don't worry about the speed of this machine, it is an old quad from early 2009 ;) - also a reason, why I cannot use cmake anymore, because support for Win7 in cmake was cancelled a while ago this year and I am stuck to it for now, so I always prefer make/makefiles)

Guenther

**Comment by SzotsGabor** [comment]
Thanks Günther. I followed your steps and have successfully compiled the source. I used this command line:

g++ *.cpp -flto -O3 -march=native -DNDEBUG -oChessPlusPlus_1.2.0-x64-SzG.exe 2>ki

Note: I always use that "2>ki" argument so that I know what went wrong.

**Comment by rwbc** [comment]
Nice that you could compile it now.

For the different cp at depth 15, there could be also some randomness used by the program (haven't checked the source),
**but** it should normally show the same nodes for the same depths (same hash size assumed, but it has no uci option for
changing hash size). That is really worrying somehow.
Can you show the output for all depths?

BTW the output with various 'tablebase hits' also cannot be right from startpos and I forgot to mention it.
Maybe it uses tbhits output for something else?

Edit: Yes it seems it counts 'tthits', when actually 'tbhits' mean endgame tablebase hits (uci specs), but that's just a minor detail
with not causing any problems.

**Comment by SzotsGabor** [comment]
This is the full output:

Chess engine by Adam Jedrych (build Nov  3 2023 15:13:33)
uci
id name @PROJECT_NAME@ @chessplusplus_VERSION@
id author Adam Jedrych

option name Logfile type string default
option name Polyglot Book type string default
option name Polyglot Sample type combo default random var random var best
uciok
position startpos
go depth 15
info depth 1 score cp 67 nodes 27 nps 27000 tbhits 0 hashfull 0 time 0 pv e2e4
info depth 2 score cp 0 nodes 115 nps 115000 tbhits 0 hashfull 0 time 0 pv e2e4 e7e5
info depth 3 score cp 34 nodes 871 nps 290333 tbhits 65 hashfull 0 time 2 pv d2d4 d7d5 g1f3
info depth 4 score cp 6 nodes 3506 nps 500857 tbhits 263 hashfull 0 time 6 pv e2e4 d7d5 b1c3 g8f6
info depth 5 score cp 31 nodes 8985 nps 641785 tbhits 351 hashfull 0 time 13 pv d2d4 d7d5 g1f3
info depth 6 score cp 0 nodes 33441 nps 760022 tbhits 1854 hashfull 4 time 43 pv d2d4 d7d5 g1f3 g8f6
info depth 7 score cp 28 nodes 56277 nps 598691 tbhits 2037 hashfull 8 time 93 pv g1f3 d7d5 d2d4 g8f6 b1c3 b8c6 c1f4
info depth 8 score cp 7 nodes 148143 nps 649750 tbhits 5208 hashfull 12 time 227 pv e2e4 d7d5 e4e5 b8c6 d2d4 a7a6 b1c3 c8f5
info depth 9 score cp 8 nodes 201225 nps 493198 tbhits 6691 hashfull 16 time 407 pv g1f3 d7d5 d2d4
info depth 10 score cp 10 nodes 840749 nps 693687 tbhits 29614 hashfull 44 time 1211 pv e2e4 d7d5 e4d5 d8d5 b1c3 d5e6 d1e2 e6e2 f1e2
info depth 11 score cp 10 nodes 524688 nps 319736 tbhits 17056 hashfull 54 time 1640 pv e2e4 d7d5 e4d5 d8d5 b1c3
info depth 12 score cp 17 nodes 1130788 nps 431269 tbhits 39035 hashfull 76 time 2621 pv e2e4 d7d5 e4d5 d8d5 b1c3 d5e6 f1e2 e6g6 g1f3 b8c6 c3b5 g6g2
info depth 13 score cp 8 nodes 3939502 nps 666582 tbhits 148599 hashfull 151 time 5909 pv g1f3 d7d5 d2d4
info depth 14 score cp 19 nodes 9070668 nps 651909 tbhits 322867 hashfull 278 time 13913 pv e2e4 d7d5 e4d5 d8d5 b1c3 d5e6 g1e2 c7c5 d2d4 c5d4
info depth 15 score cp 19 nodes 3827793 nps 224201 tbhits 156710 hashfull 321 time 17072 pv e2e4 d7d5 e4d5 d8d5 b1c3 d5e6 g1e2 c7c5 d2d4 c5d4 d1d4 b8c6 d4d3 g8f6 c1f4 a7a6
bestmove e2e4

**Comment by SzotsGabor** [comment]
Or, following your steps:

Chess engine by Adam Jedrych (build Nov  3 2023 15:13:33)
uci
id name @PROJECT_NAME@ @chessplusplus_VERSION@
id author Adam Jedrych

option name Logfile type string default
option name Polyglot Book type string default
option name Polyglot Sample type combo default random var random var best
uciok
isready
readyok
position startpos
go infinite
info depth 1 score cp 67 nodes 27 nps 27000 tbhits 0 hashfull 0 time 0 pv e2e4
info depth 2 score cp 0 nodes 115 nps 115000 tbhits 0 hashfull 0 time 0 pv e2e4 e7e5
info depth 3 score cp 34 nodes 871 nps 290333 tbhits 65 hashfull 0 time 2 pv d2d4 d7d5 g1f3
info depth 4 score cp 6 nodes 3506 nps 584333 tbhits 263 hashfull 0 time 5 pv e2e4 d7d5 b1c3 g8f6
info depth 5 score cp 31 nodes 8985 nps 641785 tbhits 351 hashfull 0 time 13 pv d2d4 d7d5 g1f3
info depth 6 score cp 0 nodes 33440 nps 760000 tbhits 1855 hashfull 2 time 43 pv d2d4 d7d5 g1f3 g8f6
info depth 7 score cp 28 nodes 56266 nps 625177 tbhits 2039 hashfull 2 time 89 pv g1f3 d7d5 d2d4 g8f6 b1c3 b8c6 c1f4
info depth 8 score cp 7 nodes 148013 nps 685245 tbhits 5236 hashfull 4 time 215 pv e2e4 d7d5 e4e5 b8c6 d2d4 a7a6 b1c3 c8f5
info depth 9 score cp 8 nodes 201308 nps 509640 tbhits 6697 hashfull 7 time 394 pv g1f3 d7d5 d2d4
info depth 10 score cp 10 nodes 929570 nps 796546 tbhits 30596 hashfull 30 time 1166 pv e2e4 d7d5 e4d5 d8d5 b1c3 d5e6 d1e2 e6e2 f1e2
info depth 11 score cp 10 nodes 442875 nps 290219 tbhits 14714 hashfull 40 time 1525 pv e2e4 d7d5 e4d5 d8d5 b1c3
info depth 12 score cp 17 nodes 1095956 nps 448243 tbhits 38568 hashfull 65 time 2444 pv e2e4 d7d5 e4d5 d8d5 b1c3 d5e6 f1e2 e6g6 g1f3 b8c6 c3b5 g6g2
info depth 13 score cp 19 nodes 1549305 nps 414807 tbhits 61561 hashfull 92 time 3734 pv e2e4 d7d5 e4d5 d8d5 b1c3 d5e6 d1e2 b8c6 g1f3 g8f6 d2d4 h7h6 c1f4 c6b4
info depth 14 score cp 9 nodes 7095313 nps 724307 tbhits 234947 hashfull 231 time 9795 pv d2d4 d7d5 b1c3 b8c6 c1f4 f7f6 g1f3 g7g5 f4g3
info depth 15 score cp 12 nodes 9552566 nps 516857 tbhits 266017 hashfull 354 time 18481 pv d2d4 d7d5 b1c3 g8f6 c1f4 h7h6 h2h4 c8f5 e2e3 b8c6 g1f3 e7e6 f1b5
info depth 16 score cp 12 nodes 10929962 nps 387793 tbhits 323681 hashfull 481 time 28184 pv d2d4 d7d5 b1c3 b8c6 c1f4 e7e6 g1f3 g8f6 e2e3 f8b4 a2a3 b4c3 b2c3 f6e4 c3c4 e4c3 d1d3

**Comment by SzotsGabor** [comment]
Adam, I have started a gauntlet for the CCRL blitz list. I still recommend you provide Windows binaries, otherwise it looks like I'm testing a private engine.

**Comment by adajed** [comment]
I've just added binaries for 1.2.0 version. Please let me know if those work for you.
Sorry for the troubles with compilation for Windows, I've always developed with Linux in mind and never tried to maintain code for Windows.
Now that I see interest in it'll fix the code to work for Windows as well :)

**Comment by SzotsGabor** [comment]
Thanks for your efforts Adam, it works.

**Comment by adajed** [comment]
> Edit: Yes it seems it counts 'tthits', when actually 'tbhits' mean endgame tablebase hits (uci specs), but that's just a minor detail with not causing any problems.

Thanks for catching this, I've already fixed this on develop branch.
