### ISSUE TITLE
Engine name and version

### ISSUE THREAD

**Issue by SzotsGabor** [adajed/chessplusplus#87]
Hi Adam,

Will you please resolve some confusion.

What is the engine name? The engine itself says it is Deep Chess while you call it chessplusplus.
Also, the version name is missing from the engine id, it would be useful to include it so that later versions could be distinguished from this one.

Gabor Szots,
CCRL testing group

BTW, how strong do you assess your engine on a CCRL scale?

**Comment by adajed** [comment]
Hi, sorry for late reply.

I forgot to change the name in code, it should be chessplusplus. I've fixed it in master already.
I've also added version, thanks!

I have no idea of its strength, I've never measured it.
I've always wanted to run it against other engines so if you have any ideas how can I do it let me know!

Thanks for interest!

**Comment by SzotsGabor** [comment]
Is it intentional to write the name "chessplusplus" (not, for example, Chessplusplus)?

**Comment by adajed** [comment]
Yes
